### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by njvack** [uwmadison-chm/scorify#12]
Python 2 is on the way out, get ready for py3.

If this involves dropping py2 support, I'm potentially okay with that.

**Comment by hugovk** [comment]
Many projects have pledged to drop Python 2.7 on or before it's EOL on 2020-01-01:

https://python3statement.org

**Comment by njvack** [comment]
Yeah, I know. We don't depend on any of those libraries, though, so if the amount of work to be compatible with both is reasonable, I'd prefer to support both 2 and 3. Our lab is still rolling py2 as our "supported" python version — though we do have python3 installed so maybe it's no big deal to deploy a py3-only module internally. I'd need to try it and see.

The biggest challenge to 2+3 compat will, of course, be unicode handling — right now scorify just chokes on non-ascii input (which is terrible) and py2's csv module is obstinately non-unicode-aware.
