### ISSUE TITLE
Allow keeping "second header" row of verbose question names

### ISSUE THREAD

**Issue by dgfitch** [uwmadison-chm/scorify#16]
Elizabeth noticed this when working in NCCAM3.

It would be good to be able to "keep around" this common row of human-readable question metadata through the scorify process.

How this would work in practice is unclear.

**Comment by dgfitch** [comment]
layout header
layout keep
layout data

**Comment by njvack** [comment]
I think we want something like

```
layout  keep
```

which would pull scored columns from that row into the output

We'll need to pair this with something in masterfile's `extract_masterfile_data` to skip these rows

**Comment by njvack** [comment]
See https://github.com/uwmadison-chm/masterfile/issues/10
