### ISSUE TITLE
No warning when using ambiguous column name

### ISSUE THREAD

**Issue by njvack** [uwmadison-chm/scorify#4]
If a column name is repeated in the input file, and we are referencing it, scorify should at least throw a warning.

**Comment by dgfitch** [comment]
Added in https://github.com/uwmadison-chm/scorify/commit/bad4c42ef686bda37edfadd431e677451bc433ac

**Comment by dgfitch** [comment]
(bad commit message, I need to improve my dang git workflow, OOPS)
